const accessGate=document.querySelector("#access-gate"),accessForm=document.querySelector("#access-form"),accessPassword=document.querySelector("#access-password"),accessError=document.querySelector("#access-error"),accessButton=document.querySelector("#access-button");
const accessHash="8fa4abdde72800faaa6a93ca9d958427bc9584fcfdfaa77a911eea752258a16f";
async function accessDigest(value){const bytes=new TextEncoder().encode(value),hash=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,"0")).join("")}
function unlockSite(){document.body.classList.remove("site-locked");accessGate.hidden=true;accessPassword.value=""}
if(sessionStorage.getItem("tplRetailAccess")==="granted")unlockSite();
accessForm.addEventListener("submit",async event=>{event.preventDefault();accessError.textContent="";accessButton.disabled=true;if(await accessDigest(accessPassword.value)===accessHash){sessionStorage.setItem("tplRetailAccess","granted");unlockSite()}else{accessError.textContent="Incorrect password.";accessPassword.select()}accessButton.disabled=false});

const state={products:[],selectedProduct:null,selectedStrength:"",cart:[]};
const $=selector=>document.querySelector(selector);
const search=$("#search"),suggestions=$("#suggestions"),categorySelect=$("#category"),catalogGroups=$("#catalog-groups"),selection=$("#selection"),selectedName=$("#selected-name"),strengthSelect=$("#strength"),prices=$("#prices"),cartCount=$("#cart-count"),orderForm=$("#order-form"),grandTotal=$("#grand-total"),submitOrder=$("#submit-order"),formStatus=$("#form-status"),cartContainer=$("#order-cart"),cartTotals=$("#order-totals");
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const strengthNumber=value=>Number.parseFloat(value)||0;
const tierInfo={one:{vials:1,label:"1 vial",discount:"Regular MSRP"},three:{vials:3,label:"3 vials",discount:"10% off"},five:{vials:5,label:"5 vials",discount:"15% off"},ten:{vials:10,label:"10 vials",discount:"20% off"}};
const categories=[
  {name:"Weight Loss",test:/semaglutide|tirzepatide|trizepatide|retatrutide|cagrilintide|cagilintide|mazdutide|survodutide|eloralintide|adipotide|aod-?9604|hgh fragment|lemon bottle|lipo lab|lipo-[bc]|lipo-c|fat blaster|5-amino/i},
  {name:"Energy & Metabolic",test:/mots|ss-?31|nad\+|aicar|slu-?pp|l-carnitine|lc120|lc216|mic\b|superhuman|humanin|vitamin b12/i},
  {name:"Recovery & Repair",test:/bpc|tb500|tb-?500|glow|klow|kpv|ll-?37|ara-?290|cartalax|bronchogen|cardiogen|vesugen|lysine-proline-valine/i},
  {name:"Growth & Performance",test:/hgh|cjc|ghrp|ipamorelin|tesamorelin|sermorelin|igf|mgf|follistatin|ace-?031|gdf-?8|mk677|epo\b/i},
  {name:"Cognitive & Mood",test:/semax|selank|dihexa|dsip|pe-?22|pinealon|cerebrolysin|cortagen|adamax|melatonin|relaxation/i},
  {name:"Sexual & Hormone",test:/pt-?141|oxytocin|hcg\b|hmg\b|kisspeptin|gonadorelin|alprostadil|testagen/i},
  {name:"Skin, Hair & Beauty",test:/melanotan|snap-?8|matrixyl|ahk-?cu|ghk-?cu|healthy hair|botulinum|hyaluronic/i},
  {name:"Immune & Wellness",test:/thym|epithalon|glutathione|foxo|pnc|vilon|crystagen|vip\b|vasoactive|dermorphin/i},
  {name:"Supplies",test:/water|saline|phosphate buffered|acetic acid/i}
];
function categoryFor(name){return categories.find(category=>category.test.test(name))?.name||"Other"}
function productStrengths(product){return[...new Set([...product.china,...product.usa].map(item=>item.strength))].sort((a,b)=>strengthNumber(a)-strengthNumber(b))}
function highestPriceItem(product,strength){const candidates=[...product.china,...product.usa].filter(item=>item.strength===strength);if(!candidates.length)return null;return{strength,retail:Object.fromEntries(Object.keys(tierInfo).map(key=>[key,Math.max(...candidates.map(item=>Number(item.retail?.[key])||0))]))}}
function matchingProducts(){const query=search.value.trim().toLowerCase();return query?state.products.filter(product=>product.name.toLowerCase().includes(query)).slice(0,12):[]}
function renderSuggestions(){const matches=matchingProducts();suggestions.hidden=!matches.length;suggestions.innerHTML=matches.map(product=>`<button type="button" data-product="${escapeHtml(product.name)}">${escapeHtml(product.name)}</button>`).join("")}
function renderCatalog(){const selected=categorySelect.value,groups=new Map();state.products.forEach(product=>{const category=categoryFor(product.name);if(selected!=="all"&&category!==selected)return;if(!groups.has(category))groups.set(category,[]);groups.get(category).push(product)});const ordered=[...categories.map(item=>item.name),"Other"];catalogGroups.innerHTML=ordered.filter(name=>groups.has(name)).map(name=>`<section class="catalog-group"><h2>${escapeHtml(name)}</h2><div class="product-buttons">${groups.get(name).sort((a,b)=>a.name.localeCompare(b.name)).map(product=>`<button type="button" data-product="${escapeHtml(product.name)}">${escapeHtml(product.name)}</button>`).join("")}</div></section>`).join("")}
function chooseProduct(name){const product=state.products.find(item=>item.name===name);if(!product)return;state.selectedProduct=product;search.value=product.name;suggestions.hidden=true;selectedName.textContent=product.name;const strengths=productStrengths(product);strengthSelect.innerHTML=strengths.map(strength=>`<option value="${escapeHtml(strength)}">${escapeHtml(strength)}</option>`).join("");state.selectedStrength=strengths[0]||"";strengthSelect.value=state.selectedStrength;selection.hidden=false;renderPrices();selection.scrollIntoView({behavior:"smooth",block:"start"})}
function priceCard(item){if(!item)return"";return`<article class="price-card"><p class="strength-copy">${escapeHtml(item.strength)} per vial</p><fieldset><legend>Choose package</legend>${Object.entries(tierInfo).map(([key,tier],index)=>`<label class="tier-choice"><input type="radio" name="package" value="${key}" ${index===0?"checked":""}><span><strong>${tier.label}</strong><small>${tier.discount}</small></span><b>${money.format(item.retail[key])}</b></label>`).join("")}</fieldset><button type="button" class="add-button" data-add>Add Selected Package to Cart</button></article>`}
function renderPrices(){if(!state.selectedProduct||!state.selectedStrength)return;prices.innerHTML=priceCard(highestPriceItem(state.selectedProduct,state.selectedStrength))}
function addToCart(){const source=highestPriceItem(state.selectedProduct,state.selectedStrength),choice=$("input[name=package]:checked");if(!source||!choice)return;const tier=tierInfo[choice.value],key=`${state.selectedProduct.name}|${source.strength}|${choice.value}`,existing=state.cart.find(item=>item.key===key);if(existing)existing.quantity++;else state.cart.push({key,name:state.selectedProduct.name,strength:source.strength,packageLabel:tier.label,discount:tier.discount,price:source.retail[choice.value],quantity:1});renderCart();formStatus.textContent=`${state.selectedProduct.name} ${source.strength}, ${tier.label}, added to your cart.`}
function subtotal(){return state.cart.reduce((sum,item)=>sum+item.price*item.quantity,0)}
function orderTotal(){return state.cart.length?subtotal()+40:0}
function orderSummary(){if(!state.cart.length)return"No items";const lines=state.cart.map(item=>`${item.quantity} x ${item.name} — ${item.strength} — ${item.packageLabel} (${item.discount}) @ ${money.format(item.price)} = ${money.format(item.quantity*item.price)}`);return`${lines.join("\n")}\nSubtotal: ${money.format(subtotal())}\nShipping: $40\nOrder total: ${money.format(orderTotal())}`}
function renderCart(){cartContainer.innerHTML=state.cart.length?state.cart.map(item=>`<div class="cart-line"><div><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.strength)} · ${item.packageLabel} · ${item.discount}</span></div><strong>${money.format(item.price*item.quantity)}</strong><div class="quantity"><button type="button" data-action="decrease" data-key="${escapeHtml(item.key)}" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button type="button" data-action="increase" data-key="${escapeHtml(item.key)}" aria-label="Increase quantity">+</button><button type="button" class="remove" data-action="remove" data-key="${escapeHtml(item.key)}">Remove</button></div></div>`).join(""):`<p class="empty">No items added.</p>`;cartTotals.hidden=!state.cart.length;cartTotals.innerHTML=state.cart.length?`<div><span>Subtotal</span><strong>${money.format(subtotal())}</strong></div><div><span>Shipping</span><strong>$40</strong></div><div class="total"><span>Order total</span><strong>${money.format(orderTotal())}</strong></div>`:"";const itemCount=state.cart.reduce((sum,item)=>sum+item.quantity,0);cartCount.textContent=`${itemCount} ${itemCount===1?"item":"items"}`;grandTotal.textContent=money.format(orderTotal());submitOrder.disabled=!itemCount;$("#order-details-field").value=orderSummary();$("#order-total-field").value=money.format(orderTotal())}

search.addEventListener("input",renderSuggestions);search.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();const first=matchingProducts()[0];if(first)chooseProduct(first.name)}});suggestions.addEventListener("click",event=>{const button=event.target.closest("[data-product]");if(button)chooseProduct(button.dataset.product)});catalogGroups.addEventListener("click",event=>{const button=event.target.closest("[data-product]");if(button)chooseProduct(button.dataset.product)});categorySelect.addEventListener("change",renderCatalog);strengthSelect.addEventListener("change",()=>{state.selectedStrength=strengthSelect.value;renderPrices()});prices.addEventListener("click",event=>{if(event.target.closest("[data-add]"))addToCart()});$(".cart-section").addEventListener("click",event=>{const button=event.target.closest("[data-action]");if(!button)return;const item=state.cart.find(entry=>entry.key===button.dataset.key);if(!item)return;if(button.dataset.action==="increase")item.quantity++;if(button.dataset.action==="decrease")item.quantity--;if(button.dataset.action==="remove"||item.quantity<=0)state.cart=state.cart.filter(entry=>entry.key!==item.key);renderCart()});
orderForm.addEventListener("submit",async event=>{event.preventDefault();if(!state.cart.length)return;submitOrder.disabled=true;submitOrder.textContent="Sending…";formStatus.textContent="Submitting your order request…";try{const response=await fetch(orderForm.action,{method:"POST",body:new FormData(orderForm),headers:{Accept:"application/json"}});if(!response.ok)throw new Error("Submission failed");state.cart=[];orderForm.reset();renderCart();formStatus.textContent="Order request sent. We will contact you to confirm availability and payment."}catch{formStatus.textContent="The order request could not be sent. Please check your information and try again."}finally{submitOrder.textContent="Submit Order Request";submitOrder.disabled=!state.cart.length}});
fetch(`/Wholesale/catalog-data.json?updated=${Date.now()}`,{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error("Catalog unavailable");return response.json()}).then(products=>{state.products=products;const names=[...new Set(products.map(product=>categoryFor(product.name)))].sort();categorySelect.insertAdjacentHTML("beforeend",names.map(name=>`<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join(""));renderCatalog()}).catch(()=>{catalogGroups.innerHTML='<div class="prompt"><strong>Catalog unavailable.</strong><span>Please refresh the page.</span></div>'});renderCart();
